# Generated by Django 4.2.14 on 2024-08-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_user_following_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
